# Generated by Django 5.0.3 on 2024-04-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0002_choice_question_delete_contact_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('consituency', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
